### ISSUE TITLE
Gauge showing "No data" for some paths

### ISSUE THREAD

**Issue by KEGustafsson** [KaappoRaivio/Scientia#2]
Paths e.g navigation.courseOverGroundTrue and navigation.speedOverGround are showing data in Gauge but navigation.headingMagnetic shows "No data".

Sample of navigation.headingMagnetic with "No data":
`{
  "meta": {
    "units": "rad",
    "description": "Current magnetic heading of the vessel, equals 'headingCompass adjusted for magneticDeviation'"
  },
  "value": 1.2479104154608804,
  "$source": "Ubuntu.II",
  "timestamp": "2020-09-06T09:20:29.591Z",
  "sentence": "HDM",
  "values": {
    "Ubuntu.II": {
      "value": 1.2479104154608804,
      "timestamp": "2020-09-06T09:20:29.591Z",
      "sentence": "HDM"
    }
  }
}`

Sample of navigation.courseOverGroundTrue, which is OK:
`{
  "meta": {
    "units": "rad",
    "description": "Course over ground (true)"
  },
  "value": 1.8980455619772132,
  "$source": "Ubuntu.GP",
  "timestamp": "2020-09-06T09:26:22.000Z",
  "sentence": "RMC"
}`

**Comment by KaappoRaivio** [comment]
Have you tried this with the latest version 0.2.1?

**Comment by KEGustafsson** [comment]
0.2.1 is showing datas, which were previously showing "No data".
Is there a way to a user to define, which unit is used for a specific gauge?
E.g. navigation.courseOverGroundTrue is showed in degrees (sk unit rad), but navigation.headingMagnetic rad (sk unit rad)?

**Comment by KaappoRaivio** [comment]
The unit conversion is incomplete at the moment. It's actually done in a sister package, [delta-procesor](https://github.com/KaappoRaivio/delta-processor/blob/master/src/UnitConverter.js). Currently the conversions are hardcoded, but they should be easy enough to migrate to a data-driven approach. The hashmap used for conversion is defined [on lines 21-31](https://github.com/KaappoRaivio/delta-processor/blob/master/src/UnitConverter.js#L21-31) . You could add your own there for the time being. 

I'll also be writing some documentation about how to set up a development environment shortly.

What comes to the ranges and zones, they directly correlate to the `meta` of the signalk spec. The most convenient way is to create a file called "defaults.json" in either your `~/.signalk/` directory (production build of the server) or in the development root directory (development build of the server), where you can define metadata for any path as you desire. [An example of such file](https://pastebin.com/9puj46uh). If you want more information, [I suggest reading the relevant parts of the spec on page 23 ondwards](signalk.org/specification/1.3.0/doc/signalk.pdf).

Keep us updated!
